// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: invitation-label/payload_messages.proto

package invitation_label

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvitationLabelBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InvitationLabelBaseResponse) Reset() {
	*x = InvitationLabelBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvitationLabelBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationLabelBaseResponse) ProtoMessage() {}

func (x *InvitationLabelBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationLabelBaseResponse.ProtoReflect.Descriptor instead.
func (*InvitationLabelBaseResponse) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{0}
}

func (x *InvitationLabelBaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateInvitationLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateInvitationLabelRequest) Reset() {
	*x = CreateInvitationLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInvitationLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationLabelRequest) ProtoMessage() {}

func (x *CreateInvitationLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitationLabelRequest) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInvitationLabelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvitationLabelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllInvitationLabelByUserIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Search *string `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Page   *int32  `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit  *int32  `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *GetAllInvitationLabelByUserIDRequest) Reset() {
	*x = GetAllInvitationLabelByUserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInvitationLabelByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvitationLabelByUserIDRequest) ProtoMessage() {}

func (x *GetAllInvitationLabelByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvitationLabelByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllInvitationLabelByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllInvitationLabelByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllInvitationLabelByUserIDRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetAllInvitationLabelByUserIDRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *GetAllInvitationLabelByUserIDRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type InvitationLabelPaging struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPage int32 `protobuf:"varint,1,opt,name=current_page,proto3" json:"current_page,omitempty"`
	TotalPage   int32 `protobuf:"varint,2,opt,name=total_page,proto3" json:"total_page,omitempty"`
	Count       int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *InvitationLabelPaging) Reset() {
	*x = InvitationLabelPaging{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvitationLabelPaging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationLabelPaging) ProtoMessage() {}

func (x *InvitationLabelPaging) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationLabelPaging.ProtoReflect.Descriptor instead.
func (*InvitationLabelPaging) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{3}
}

func (x *InvitationLabelPaging) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *InvitationLabelPaging) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *InvitationLabelPaging) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetAllInvitationLabelByUserIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message          string                            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	InvitationLabels []*GetInvitationLabelByIDResponse `protobuf:"bytes,2,rep,name=invitation_labels,proto3" json:"invitation_labels,omitempty"`
	Paging           *InvitationLabelPaging            `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *GetAllInvitationLabelByUserIDResponse) Reset() {
	*x = GetAllInvitationLabelByUserIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInvitationLabelByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvitationLabelByUserIDResponse) ProtoMessage() {}

func (x *GetAllInvitationLabelByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvitationLabelByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllInvitationLabelByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllInvitationLabelByUserIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllInvitationLabelByUserIDResponse) GetInvitationLabels() []*GetInvitationLabelByIDResponse {
	if x != nil {
		return x.InvitationLabels
	}
	return nil
}

func (x *GetAllInvitationLabelByUserIDResponse) GetPaging() *InvitationLabelPaging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type GetInvitationLabelByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetInvitationLabelByIDRequest) Reset() {
	*x = GetInvitationLabelByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInvitationLabelByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitationLabelByIDRequest) ProtoMessage() {}

func (x *GetInvitationLabelByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitationLabelByIDRequest.ProtoReflect.Descriptor instead.
func (*GetInvitationLabelByIDRequest) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvitationLabelByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInvitationLabelByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,proto3,oneof" json:"deleted_at,omitempty"`
}

func (x *GetInvitationLabelByIDResponse) Reset() {
	*x = GetInvitationLabelByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInvitationLabelByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitationLabelByIDResponse) ProtoMessage() {}

func (x *GetInvitationLabelByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitationLabelByIDResponse.ProtoReflect.Descriptor instead.
func (*GetInvitationLabelByIDResponse) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvitationLabelByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInvitationLabelByIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInvitationLabelByIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInvitationLabelByIDResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetInvitationLabelByIDResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetInvitationLabelByIDResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UpdateInvitationLabelByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateInvitationLabelByIDRequest) Reset() {
	*x = UpdateInvitationLabelByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInvitationLabelByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvitationLabelByIDRequest) ProtoMessage() {}

func (x *UpdateInvitationLabelByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvitationLabelByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvitationLabelByIDRequest) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInvitationLabelByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInvitationLabelByIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteInvitationLabelByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteInvitationLabelByIDRequest) Reset() {
	*x = DeleteInvitationLabelByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invitation_label_payload_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInvitationLabelByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInvitationLabelByIDRequest) ProtoMessage() {}

func (x *DeleteInvitationLabelByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_label_payload_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInvitationLabelByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteInvitationLabelByIDRequest) Descriptor() ([]byte, []int) {
	return file_invitation_label_payload_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteInvitationLabelByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_invitation_label_payload_messages_proto protoreflect.FileDescriptor

var file_invitation_label_payload_messages_proto_rawDesc = []byte{
	0x0a, 0x27, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x2f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x37, 0x0a, 0x1b, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x1c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x24, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x02, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x71, 0x0a, 0x15, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xcc, 0x01,
	0x0a, 0x25, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x53, 0x0a, 0x11, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x11, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x2f, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa6, 0x02,
	0x0a, 0x1e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0x46, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32,
	0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_invitation_label_payload_messages_proto_rawDescOnce sync.Once
	file_invitation_label_payload_messages_proto_rawDescData = file_invitation_label_payload_messages_proto_rawDesc
)

func file_invitation_label_payload_messages_proto_rawDescGZIP() []byte {
	file_invitation_label_payload_messages_proto_rawDescOnce.Do(func() {
		file_invitation_label_payload_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_invitation_label_payload_messages_proto_rawDescData)
	})
	return file_invitation_label_payload_messages_proto_rawDescData
}

var file_invitation_label_payload_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_invitation_label_payload_messages_proto_goTypes = []any{
	(*InvitationLabelBaseResponse)(nil),           // 0: proto.InvitationLabelBaseResponse
	(*CreateInvitationLabelRequest)(nil),          // 1: proto.CreateInvitationLabelRequest
	(*GetAllInvitationLabelByUserIDRequest)(nil),  // 2: proto.GetAllInvitationLabelByUserIDRequest
	(*InvitationLabelPaging)(nil),                 // 3: proto.InvitationLabelPaging
	(*GetAllInvitationLabelByUserIDResponse)(nil), // 4: proto.GetAllInvitationLabelByUserIDResponse
	(*GetInvitationLabelByIDRequest)(nil),         // 5: proto.GetInvitationLabelByIDRequest
	(*GetInvitationLabelByIDResponse)(nil),        // 6: proto.GetInvitationLabelByIDResponse
	(*UpdateInvitationLabelByIDRequest)(nil),      // 7: proto.UpdateInvitationLabelByIDRequest
	(*DeleteInvitationLabelByIDRequest)(nil),      // 8: proto.DeleteInvitationLabelByIDRequest
	(*timestamppb.Timestamp)(nil),                 // 9: google.protobuf.Timestamp
}
var file_invitation_label_payload_messages_proto_depIdxs = []int32{
	6, // 0: proto.GetAllInvitationLabelByUserIDResponse.invitation_labels:type_name -> proto.GetInvitationLabelByIDResponse
	3, // 1: proto.GetAllInvitationLabelByUserIDResponse.paging:type_name -> proto.InvitationLabelPaging
	9, // 2: proto.GetInvitationLabelByIDResponse.created_at:type_name -> google.protobuf.Timestamp
	9, // 3: proto.GetInvitationLabelByIDResponse.updated_at:type_name -> google.protobuf.Timestamp
	9, // 4: proto.GetInvitationLabelByIDResponse.deleted_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_invitation_label_payload_messages_proto_init() }
func file_invitation_label_payload_messages_proto_init() {
	if File_invitation_label_payload_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_invitation_label_payload_messages_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InvitationLabelBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateInvitationLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllInvitationLabelByUserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InvitationLabelPaging); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllInvitationLabelByUserIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetInvitationLabelByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetInvitationLabelByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateInvitationLabelByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invitation_label_payload_messages_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteInvitationLabelByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_invitation_label_payload_messages_proto_msgTypes[2].OneofWrappers = []any{}
	file_invitation_label_payload_messages_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_invitation_label_payload_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invitation_label_payload_messages_proto_goTypes,
		DependencyIndexes: file_invitation_label_payload_messages_proto_depIdxs,
		MessageInfos:      file_invitation_label_payload_messages_proto_msgTypes,
	}.Build()
	File_invitation_label_payload_messages_proto = out.File
	file_invitation_label_payload_messages_proto_rawDesc = nil
	file_invitation_label_payload_messages_proto_goTypes = nil
	file_invitation_label_payload_messages_proto_depIdxs = nil
}
